sudo: false
language: erlang
otp_release:
  - 18.0
before_script: "./rebar3 update"
script: "./rebar3 dialyzer"
cache:
  directories:
  - $HOME/.cache/rebar3/
deploy:
  provider: script
  script: scripts/hex.sh
  on:
    tags: true