version: '3'
services:
    elasticsearch:
        image: elasticsearch:5.3.2-alpine
        ports:
            - 9200:9200
        volumes:
          - elasticsearch-data:/usr/share/elasticsearch/data
        environment:
            ES_JAVA_OPTS: "-Xms500m -Xmx500m"
volumes:
    elasticsearch-data: {}
